### ISSUE TITLE
Add new badges for views/week and clones/week

### ISSUE THREAD

**Issue by MuYunyun** [yi-Xu-0100/traffic-to-badge#29]
![image](https://user-images.githubusercontent.com/19354791/97973084-7bc0d380-1e00-11eb-9899-0598aa93dda1.png)

Hi brother, I wonder the analyze time of the view counts, is it since the project is created or using the traffic-to-badge Github action?

**Comment by yi-Xu-0100** [comment]
Yes, the GitHub only provides 2 weeks traffic data. But I combine traffic with branch traffic that backed up before.

It also means the traffic data can be modified by yourself, and only two weeks traffic data which got from API every time can be guaranteed to be official data.

**Comment by MuYunyun** [comment]
> @MuYunyun The GitHub only provides two weeks traffic data, but the action combine traffic with `traffic_branch` that backed up before.
> 
> It also means the traffic data can be modified by yourself, and only two weeks traffic data which got from API every time can be guaranteed to be official data.
> 
> The two weeks traffic data also can be seen from `insight/traffic` with repository.
> 
> I will point it out with next release.

thanks, I get.

**Comment by MuYunyun** [comment]
the indicators about `pv/weeks` or `pv/day` maybe be more accurate and useful through official data, is it? Could you add the indicator about `pv/weeks` in this project?

**Comment by yi-Xu-0100** [comment]
It is a good idea to show the official traffic data. Thanks for your advice and I will add a badge for `pv/week`.

Because the traffic data in today will change in every time, and we can't refresh the badge with action schedule(too often). I will set the `pv/week` for only the data in one week before today.

**Comment by yi-Xu-0100** [comment]
> Because the traffic data in today will change in every time, and we would not refresh the badge with action schedule(too often).

For the same reason, I will remove today's data from the latest data, and it will not be backed up.

**Comment by MuYunyun** [comment]
> It is a good idea to show the official traffic data. Thanks for your advice and I will add a badge for `pv/week`.
> 
> Because the traffic data in today will change in every time, and we would not refresh the badge with action schedule(too often). I will set the `pv/week` for only the data in one week before today.

can't wait for using it! :smile:

**Comment by yi-Xu-0100** [comment]
[![views](https://raw.githubusercontent.com/yi-Xu-0100/traffic-to-badge/traffic/traffic-traffic-to-badge/views.svg)](https://github.com/yi-Xu-0100/traffic-to-badge/tree/traffic#-traffic-to-badge) [![views](https://raw.githubusercontent.com/yi-Xu-0100/traffic-to-badge/traffic/traffic-traffic-to-badge/views_per_week.svg)](https://github.com/yi-Xu-0100/traffic-to-badge/tree/traffic#-traffic-to-badge) [![clones](https://raw.githubusercontent.com/yi-Xu-0100/traffic-to-badge/traffic/traffic-traffic-to-badge/clones.svg)](https://github.com/yi-Xu-0100/traffic-to-badge/tree/traffic#-traffic-to-badge) [![clones](https://raw.githubusercontent.com/yi-Xu-0100/traffic-to-badge/traffic/traffic-traffic-to-badge/clones_per_week.svg)](https://github.com/yi-Xu-0100/traffic-to-badge/tree/traffic#-traffic-to-badge)

I add test for main branch. If there is no problem, I will release for next day.

**Comment by yi-Xu-0100** [comment]
see in <https://github.com/marketplace/actions/traffic-to-badge>

**Comment by MuYunyun** [comment]
> see in https://github.com/marketplace/actions/traffic-to-badge

Thanks. I use views/week successfully in 1.2.0 version, you should update the version in https://github.com/marketplace/actions/traffic-to-badge

![image](https://user-images.githubusercontent.com/19354791/98326249-c2dedc80-202b-11eb-9dee-30c6579dd1e5.png)

**Comment by yi-Xu-0100** [comment]
Well, I forgot again. 😆
